# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe6ab2df52065aab59e466f899a3b63d8d474e427bc60077d960e24a53daaef37a23718f1efb52ee758fac5fee00b1ab8af6208dfffe7fa905bc06ae1f3c2e3

test:
  secret_key_base: 0d2a37d9275a6726963618bb579ab5eb1157b1540ef748d9e96de12d198a814fcab8105beac4e89b70bb9ea1bf90995e784e6e31e564ffe391c75df7ed281758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
